server:
  port: 7070
  
spring:
  application:    name: microservice-config-server-eureka  cloud:    config:      server:        git:          uri: https://github.com/cddofficial/cloud-config-git-repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true  #显示真实ip，不是必须的    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}  #实例id，如， 实力id:端口号        